### ISSUE TITLE
Need to enter on-time boot menu every cold boot on Dell Latitude

### ISSUE THREAD

**Issue by fedegiova** [ChubbyAnt/sedutil#14]
Hi,

thanks for you work. I've successfully installed seduti on  a Dell Latitude e5530,  with a Samsung 860 EVO SSD. Unlocking ad booting works but I have to manually press F12 on every cold boot to manually  select the PBA from the UEFI boot menu, otherwise I get an error about the bios not being able to find a boot disk.

I've created the PBA entry and the unlocked GRUB entry from the BIOS main menu but it doesn't help.

This is the current configuration. Secure boot is disabled.
`
$ sudo efibootmgr -v
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0001
Boot0000* Manjaro	PciRoot(0x0)/Pci(0x1f,0x2)/Sata(0,65535,0)/HD(1,GPT,f8c45168-c4de-dd4b-8cd4-cd9b7894745a,0x10000,0x74000)/File(\EFI\Manjaro\grubx64.efi)
Boot0001* PBA	PciRoot(0x0)/Pci(0x1f,0x2)/Sata(0,65535,0)/HD(1,GPT,cb56fd69-7538-48e9-91ac-e36e5f64db68,0x800,0xf7df)/File(\EFI\boot\bootx64.efi)
`
any idea?

Regards. Federico

**Comment by ChubbyAnt** [comment]
Did you find a resolution?

**Comment by fedegiova** [comment]
Yes. I've changed the boot priority, not sure why it has been relevant but now it's working fine.
Great software, I've showed it to my IT department which was enthusiastic
