### ISSUE TITLE
Continue boot sequence after exit UEFI shell

### ISSUE THREAD

**Issue by chouex** [ChubbyAnt/sedutil#16]
after login UEFI shell `DriveTrust login: root`, I tried `exit` expecting UEFI exit and next boot drive continue, but I come back UEFI and show `DriveTrust login` again,

I tried to recompile from source but I cant find what to change to allow me exit UEFI shell and continue boot windows.

what I really want is recompile my own usb boot drive(key):
after rootfs loaded
1. check if the drive is unlocked by sedutil --query ... (by modified S99pba.sh)
2. if drive is not unlock tryunlock by linuxpba(i modify the source so it will not reboot after unlock)
3. continue boot next device (BIOS boot order) without reboot(I dont know how)

**Comment by ChubbyAnt** [comment]
It looks like you are trying to, at cold boot:

(1) Unlock a SEDutil locked drive, then 
(2) boot to a non-SEDutil locked drive. 

If so, assuming that the SEDutil locked drive is not bootable, then the UEFI should cycle automatically to the next drive and boot that drive. 

If you are trying to unlock two drives, you can always setup SEDutil to lock 2 drives, and so long as they are using the same password, once the password is entered after cold boot SEDutil will unlock the 2 SEDutil locked drives.

**Comment by chouex** [comment]
I only have one drive encrypted, I am trying to decrypt it using usb thumb drive
Just want to boot the decrypted nvme drive from usb thumb drive without reboot.

**Comment by ChubbyAnt** [comment]
SEDutil always requires reboot after unlocking. You can unlock with the USB drive, then remove the drive during the reboot cycle and the unlocked drove will boot.

**Comment by chouex** [comment]
got it
