### ISSUE TITLE
Sedutil on Lenovo Yoga 2 Pro

### ISSUE THREAD

**Issue by sollermun** [ChubbyAnt/sedutil#21]
I want to use sedutil on a Lenovo Yoga 2 Pro with a Kingston SUV500MS. I was able to successfully boot to a rescue USB and follow the instructions without any error messages. When I power off and reboot, I am able to enter my password. However, after the password no boot device is found.  I disabled secure boot and fast boot. This does not seem to help. Any help would be appreciated.

**Comment by ChubbyAnt** [comment]
Assuming you finish setting up the PBA, then poweroff, then cold start, what happens after you enter your password, exactly?

**Comment by ChubbyAnt** [comment]
See this: https://github.com/ChubbyAnt/sedutil/issues/23
