### ISSUE TITLE
Makefile.am references incorrect sha files

### ISSUE THREAD

**Issue by DarkSpyro003** [ChubbyAnt/sedutil#3]
Makefile.am references the files:
Common/pbkdf2/sha1.c
Common/pbkdf2/sha1.h
But you replaced these with:
Common/pbkdf2/sha2.h
Common/pbkdf2/sha512.c

You should also make this change in Makefile.am, otherwise make all will fail.

https://github.com/ChubbyAnt/sedutil/blob/7cafbda7cbfd7027d5dc62cfecc6a5dfbea6d385/Makefile.am#L20-L21

**Comment by ChubbyAnt** [comment]
Good catch. 

Corrected with https://github.com/ChubbyAnt/sedutil/commit/db1e9ba6f2595e06149ced35b9a3957cd151f3da

To test, built on Ubuntu 18.04.3 from source with no errors to confirm the fix you noted is working. 

Thank you!
