### ISSUE TITLE
Remove OPAL (--revertnoerase) Fails

### ISSUE THREAD

**Issue by mabachel** [ChubbyAnt/sedutil#4]
Hey,

I did not specifically tested your RESCUE64.img to Remove OPAL since I suspect it is not compatible due to SHA512 use instead of SHA1 but because your source is based on DTA's version 1.15.1 which I use, I guess your version is also affected.

Check out the issue here: https://github.com/Drive-Trust-Alliance/sedutil/issues/304#issue-502612800
and here: https://github.com/ladar/sedutil/issues/11#issue-502616593

**Comment by ChubbyAnt** [comment]
Thanks for the heads up.

Remove OPAL on this repo is working on the EVO 850 in a T470 Thinkpad. We;ll keep an eye on this Issue.

**Comment by mabachel** [comment]
May I have to set some flags differently first? Can you compare a query of your 850 EVO with my query to check it, please?

**Comment by rvanlaar** [comment]
It seems you first need to disable locking, and set mbrenable to off:

> sedutil-cli --disablelockingrange 0 PASSWORD /dev/nvme0
> sedutil-cli --setmbrenable off PASSWORD /dev/nvme0
> sedutil-cli --revertnoerase PASSWORD /dev/nvme0
> sedutil-cli --reverttper PASSWORD /dev/nvme0

Beware with the reverttper command. 
Please read the information on: https://sedutil.com/

**Comment by ChubbyAnt** [comment]
@mabachel we don't have the 850 T470 setup anymore.

Did you get the issue resolved?

**Comment by mabachel** [comment]
> It seems you first need to disable locking, and set mbrenable to off:
> 
> > sedutil-cli --disablelockingrange 0 PASSWORD /dev/nvme0
> > sedutil-cli --setmbrenable off PASSWORD /dev/nvme0
> > sedutil-cli --revertnoerase PASSWORD /dev/nvme0
> > sedutil-cli --reverttper PASSWORD /dev/nvme0
> 
> Beware with the reverttper command.
> Please read the information on: https://sedutil.com/

Thanks! It worked like a charm for me. The Documentation / Wiki should mention this.

This issue can be closed.

**Comment by ChubbyAnt** [comment]
Thank you!

**Comment by hardhub** [comment]
> 
> 
> It seems you first need to disable locking, and set mbrenable to off:
> 
> > sedutil-cli --disablelockingrange 0 PASSWORD /dev/nvme0
> > sedutil-cli --setmbrenable off PASSWORD /dev/nvme0
> > sedutil-cli --revertnoerase PASSWORD /dev/nvme0
> > sedutil-cli --reverttper PASSWORD /dev/nvme0
> 
> Beware with the reverttper command.
> Please read the information on: https://sedutil.com/

I think the latest command issue is better described here: https://github.com/Drive-Trust-Alliance/sedutil/wiki/Remove-OPAL
