### ISSUE TITLE
PBA not bootable when using NVMe drive

### ISSUE THREAD

**Issue by fnunez1985** [ChubbyAnt/sedutil#42]
Hi all,

For whatever reason my TCG Opal NVMe SSD cannot boot from the UEFI PBA. I followed the instructions [here](https://github.com/ChubbyAnt/sedutil) and everything worked fine except when trying to boot from the UEFI PBA. That does not work, BIOS cannot find a bootable drive.
I can manually boot the UEFI RESCUE USB drive and manually unlock the NVMe just fine. After that, the unlocked NVMe boots fine into the Ubuntu OS, however the PBA will never boot. I have checked MBRenable is Y and MBRDone is N at boot time so it should work. At least this works with another SATA SSD so I guess it is related/specific to the NVMe.
I assume BIOS settings are fine if I can boot from the drive when it is manually unlocked but not the PBA? Any idea what could I be doing wrong?
Thanks in advance!

**Comment by neo125874** [comment]
@fnunez1985 hi, did you have the solution of this issue?

**Comment by fnunez1985** [comment]
No, still not working for me but I keep digging, hopefully I will have more info on this soon enough. To give you the latest, I was able to get a newer firmware for the NVMe but unfortunately that did not work to fix this issue.
For me it is low priority as I can work around the issue not using the PBA and lock/unlock the drive using BIOS but I keep investigated in the background and plan to find out what is wrong.

**Comment by fnunez1985** [comment]
Turned to be a BIOS issue. A newer BIOS does not show the issue. Closing this now.
