### ISSUE TITLE
Wouldn't boot into windows

### ISSUE THREAD

**Issue by rvanlaar** [ChubbyAnt/sedutil#5]
Thank you for maintaining this software and for the documentation on sedutil.com.
Installing sedutil was a breeze. 

There was a problem with the booting process.
The boot process stopped after typing in my password.
The password was correct and it shows that the disk was unlocked.

Removing OPAL all together made me boot back into windows again.

**Comment by ChubbyAnt** [comment]
What hardware? 

Some very modern enterprise laptops have a "security feature" that shuts off the hard drive or NVME drive upon reboot - like a mini full shutdown - which resets the hard drive encryption after SEDutil unlocks the drive.  But, almost all of the laptops that have this "security feature" also offer their own enterprise-class TCG OPAL software.

**Comment by ChubbyAnt** [comment]
Cold case. Closed.
